### ISSUE TITLE
Potential performance increases using SIMD instructions on x86 processors and parallel HashMaps?

### ISSUE THREAD

**Issue by jelber2** [cschin/peregrine-2021#10]
Just leaving this here as potential means of additional performance increases using the following crates:

1. taking advantage of SIMD instruction sets on x86 cpus only (https://docs.rs/simdeez/latest/simdeez/)

    - might be implementable for some functions **EDIT: simdeez does not currently support vectors with u8.**

3. taking advantage of all multi-core cpus architectures for HashMaps (https://docs.rs/dashmap/latest/dashmap/index.html)

    - not sure if current algorithm can take advantage of dashmap or not **EDIT:  most steps with HashMaps are using chunks for parallel processing anyway**

**Comment by cschin** [comment]
@jelber2 I did evaluate a couple of hash libraries when I start this codebase. I ended up using the FxHash (https://docs.rs/fxhash/0.2.1/fxhash/). The default Rust hashing is designed for security not for performance. The FxHash has a bit better performance. I do like to take a look into the dashmap. One way to do it to take one of the modules and try it out there. Maybe we can have a separate experimental branch for testing it out.

**Comment by cschin** [comment]
One other consideration is, I did like to run on other architecture, for example, the AWS graviton CPUs.

**Comment by jelber2** [comment]
@cschin I agree that maybe it would be best to avoid SIMD-only compilation, but I think `simdeez` has a scalar fall back that could be used by ARM cpus, but I am not sure if SIMD would really be of much benefit now that I think of it. In terms of `dashmap`, I think it really only shines when there are multiple cores/threads utilized and as `peregrine-2021` breaks most of the hash-related steps into chunks, I am now thinking `dashmap` might not really be useful either.
