### ISSUE TITLE
read_shmmr_index size: 0 

### ISSUE THREAD

**Issue by matthewhvandam** [cschin/peregrine-2021#13]
Hello, 

I suspect the "read_shmmr_index " part is not finding my reads for some reason. I pasted an abbreviated log file below. The data may be on the low side for coverage depth, not sure if that is the problem. Thank you very much for any help you can provide and for writing this program. 

Best,
Matt

  [pg_asm] pg_asm peregrine-r 0.4.13 (main:593f930, release build, linux [x86_64] [rustc 1.58.1 (db9d1b20b 2022-01-20)])
  [pg_asm] command: pg_asm p_amabilis_all_cells.fastq.lst p_amabilis_pg_asm_out 64
  [pg_asm] current dir: /home3/mvd/ont/experiment/pachy_run1_guppy9.4/basecalls
  [pg_asm] pg_asm run start
  [pg_asm::utils] BGN: pg_asm : (maxRSS, utime, stime): 4040 0 0
  [pg_asm] pg_asm run parameters: w:80, k:56, r:6, tol:0.01 bestn:6
  [pg_asm] faster mode: false
  [pg_asm] use layout method: 2
  [pg_asm] keep intermediate files: false
  [pg_asm] number of threads: 64
  [pg_asm] number of chunks: 128
  [pg_asm] input read file: p_amabilis_all_cells.fastq.lst
  [pg_asm] working directory: p_amabilis_pg_asm_out
  [pg_asm] sys: number of physical CPU cores detected: 128
  [pg_asm] sys: total memory: 2109390820 KB
  [pg_asm] sys: used memory: 13426928 KB
  [pg_asm] sys: total swap: 3907016700 KB
  [pg_asm] sys: used swap: 0 KB
  [pg_asm::utils] BGN: get_ovlp, input_reads: p_amabilis_all_cells.fastq.lst : (maxRSS, utime, stime): 14276 4 109
  [pg_asm::utils] BGN: bulding sequence database : (maxRSS, utime, stime): 14276 4 109
  [pg_asm::utils::build_sdb] create seq db: p_amabilis_pg_asm_out/reads.seqdb
  [pg_asm::utils::build_sdb] create seq index: p_amabilis_pg_asm_out/reads.idx
  [pg_asm::utils::build_sdb] get input files from: p_amabilis_all_cells.fastq.lst
  [pg_asm::utils::build_sdb] input file: /home/mvd/ont/experiment/pachy_run1_guppy9.4/basecalls/p_amabilis_all_cells.fastq
  [pg_asm::utils::build_sdb] total number of reads indexed: 1902708
  [pg_asm::utils::build_sdb] total number of bases: 16243520035
  [pg_asm::utils::build_sdb] average read length: 8537.054
  [pg_asm::utils] END: bulding sequence database : (maxRSS, utime, stime): 42585524 709 682
  [pg_asm::utils] BGN: bulding shimmer : (maxRSS, utime, stime): 42585524 709 682
  [pg_asm::utils] END: bulding shimmer : (maxRSS, utime, stime): 58735548 1028 685
  [pg_asm::utils] BGN: overlapping : (maxRSS, utime, stime): 58735548 1028 685
  [pg_asm::utils::ovlp] read_shmmr_index size: 0
  [pg_asm::utils::ovlp] smp_index: 0
  [pg_asm::utils::ovlp] remove 0 singletons from smp_index
  [pg_asm::utils::ovlp] smp_index size updated: 0
  [pg_asm::utils::ovlp] read seq idx: p_amabilis_pg_asm_out/reads.seqdb
  [pg_asm::utils::ovlp] read seq db: p_amabilis_pg_asm_out/reads.seqdb
  [pg_asm::utils] END: overlapping : (maxRSS, utime, stime): 58735548 1030 858
  [pg_asm::utils] END: get_ovlp - input_reads: p_amabilis_all_cells.fastq.lst : (maxRSS, utime, stime): 58735548 1030 858
  [pg_asm::utils] BGN: ovlp_ec : (maxRSS, utime, stime): 58735548 1030 858
  [pg_asm::utils::ovlp_ec] read seq idx: p_amabilis_pg_asm_out/reads.seqdb
  [pg_asm::utils::ovlp_ec] read seq db: p_amabilis_pg_asm_out/reads.seqdb
  [pg_asm::utils::ovlp_ec] prefix: p_amabilis_pg_asm_out/reads-ovlp
  [pg_asm::utils::ovlp_ec] out_prefix: p_amabilis_pg_asm_out/ec_read
  [pg_asm::utils] END: ovlp_ec : (maxRSS, utime, stime): 58735548 1030 858
  [pg_asm] remove p_amabilis_pg_asm_out/reads-ovlp.01
  [pg_asm] remove p_amabilis_pg_asm_out/reads-ovlp.02
...
  [pg_asm] remove p_amabilis_pg_asm_out/reads-ovlp.97
  [pg_asm] remove p_amabilis_pg_asm_out/reads-ovlp.98
  [pg_asm] remove p_amabilis_pg_asm_out/reads-ovlp.99
  [pg_asm] remove p_amabilis_pg_asm_out/reads-shmr-01-of-128.dat
  [pg_asm] remove p_amabilis_pg_asm_out/reads-shmr-02-of-128.dat
...
  [pg_asm] remove p_amabilis_pg_asm_out/reads-shmr-98-of-128.dat
  [pg_asm] remove p_amabilis_pg_asm_out/reads-shmr-99-of-128.dat
  [pg_asm] remove p_amabilis_pg_asm_out/reads.seqdb
  [pg_asm] remove p_amabilis_pg_asm_out/reads.idx
  [pg_asm] input reads: p_amabilis_pg_asm_out/ec_reads.lst
  [pg_asm] working directory: p_amabilis_pg_asm_out
  [pg_asm::utils] BGN: get_ovlp, input_reads: p_amabilis_pg_asm_out/ec_reads.lst : (maxRSS, utime, stime): 58735548 1030 859
  [pg_asm::utils] BGN: bulding sequence database : (maxRSS, utime, stime): 58735548 1030 859
  [pg_asm::utils::build_sdb] create seq db: p_amabilis_pg_asm_out/ec_reads.seqdb
  [pg_asm::utils::build_sdb] create seq index: p_amabilis_pg_asm_out/ec_reads.idx
  [pg_asm::utils::build_sdb] get input files from: p_amabilis_pg_asm_out/ec_reads.lst
  [pg_asm::utils::build_sdb] input file: p_amabilis_pg_asm_out/ec_read_01.fa
  [pg_asm::utils::build_sdb] input file: p_amabilis_pg_asm_out/ec_read_01.fa may not be proper input file (filesize = 0), ignore
  [pg_asm::utils::build_sdb] input file: p_amabilis_pg_asm_out/ec_read_02.fa
  [pg_asm::utils::build_sdb] input file: p_amabilis_pg_asm_out/ec_read_02.fa may not be proper input file (filesize = 0), ignore
  [pg_asm::utils::build_sdb] input file: p_amabilis_pg_asm_out/ec_read_03.fa
...
  [pg_asm::utils::build_sdb] input file: p_amabilis_pg_asm_out/ec_read_99.fa
  [pg_asm::utils::build_sdb] input file: p_amabilis_pg_asm_out/ec_read_99.fa may not be proper input file (filesize = 0), ignore
  [pg_asm::utils::build_sdb] total number of reads indexed: 0
  [pg_asm::utils::build_sdb] total number of bases: 0
  [pg_asm::utils::build_sdb] average read length: NaN
  [pg_asm::utils] END: bulding sequence database : (maxRSS, utime, stime): 58735548 1030 859
  [pg_asm::utils] BGN: bulding shimmer : (maxRSS, utime, stime): 58735548 1030 859
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: "memory map must have a non-zero length" }', src/bin/utils/build_idx.rs:106:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by jelber2** [comment]
I think I have run into this error before when trying to use lower quality reads that did not meet the ~>99.5 % accuracy expected by `peregrine-2021`. One can use PacBio HiFi reads and sometimes error-corrected PacBio or Nanopore reads (but see my comment about error-corrected reads with `peregrine-2021` https://github.com/cschin/peregrine-2021/issues/2) Are you using raw Nanopore reads based on your file names?

**Comment by matthewhvandam** [comment]
Hi Jean,
Thank you for your reply!
The reads are from the ONT Q20 chemistry on R10.4. Did not realize the accuracy requirements were so stringent.

Thanks for the help.

**Comment by jelber2** [comment]
@matthewhvandam you could try https://github.com/fenderglass/Flye with the `--nano-hq` option as well

**Comment by jelber2** [comment]
@matthewhvandam , have you tried using the duplex base calling algorithm? That might help to be able to run `peregrine-2021`, you might also be able to use [vechat](https://github.com/HaploKit/vechat) (if you have access to several GPUs, I made a pull request to enable Racon GPU support https://github.com/HaploKit/vechat/pull/1, I found the `--base` option to take too long). Also, [br](https://github.com/natir/br/) is super fast, but one can only use up to k=19 effectively (unless you have access to > 2TB RAM for k=21). It worked great for PacBio HiFi reads for bacterial genomes for me. The documentation for `br` is a little sparse at the moment.

Running/Installing `br` - requires input as FASTA
```bash
mkdir -p ~/git
cd ~/git

git clone https://github.com/natir/br.git
cd br
# I had to remove this file to compile, even though I had RUST 1.59.0
rm rust-toolchain.toml
cargo build --release

# run br with k=19 and the graph correction algorithm - seemed fine for me for haploid genomes,
# don't have a diploid dataset at the moment to test it with
~/git/br/target/release/br -k 19 -i input.fasta -o output.fasta -m graph
```
then maybe try running `peregrine-2021`
