### ISSUE TITLE
pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by ccmeth** [cschin/peregrine-2021#16]
Hi,
Thanks for providing such useful tool. Recently I met with an issue when using peregrine:
pkg_resources.DistributionNotFound: The 'numpy>=1.16.2' distribution was not found and is required by peregrine

Could you please tell me how to solve it?

**Comment by ccmeth** [comment]
Hovever, I installed numpy with 1.25 but still could not solve this problem.

**Comment by cschin** [comment]
@ccmeth  the peregrine-2021 is pure Rust code, it does not use numpy. I assume you install through bioconda which might introduce some unwanted dependence. Can you try to compile or download the binary distribution?

**Comment by jelber2** [comment]
@ccmeth , are you trying to install the original peregrine?

**Comment by cschin** [comment]
@ccmeth still have a problem?

**Comment by ccmeth** [comment]
> @ccmeth still have a problem?

Thanks for your kind suggestion and the problem has been solved.
