### ISSUE TITLE
Does Peregrine-2021 work with PacBio CLR and Nanopore reads?  

### ISSUE THREAD

**Issue by agesantos** [cschin/peregrine-2021#2]
Dear Dr Chin, 

Peregrine-2021 seems to be a fantastic option and I am very interested in using it. The fact that it tries to keep high repeat content assembled is of particular interest for my case of study. 
All the results you presented used PacBio Hi-Fi reads, which also fits some of my work. However, I was wondering if it could be used to produce assemblies of reads with higher error content, i.e., PacBio CLR or Nanopore reads? Have you ever tested it? Do you think it is a viable option? 

Finally, and sorry if this is a basic question, but when running the assembly, is there any calculation I should do to optimise the ARGS for the Number of threads and Number of partitions. i.e., I have a machine with 512 GB of RAM and 30 CPUs. Should I simply specify 30 for NTHREADS? What about the partition? 

Hope you can help me,
My best regards,
André

**Comment by cschin** [comment]
@agesantos My understanding is that PacBio is phasing out CLR and Nanopore wants to increase their accuracy to compete with PacBio's CCS. The current Peregrine-2021 only supports more accurate reads (> 99.5%) as the current indexing method is more effective for those. If you are interested in repeats, lower than that actually will make the assembly computing much much longer and it would be more complicated to interpret the results. (On the other hand, the super long-read from ONT will help a lot in comparison to 10kb or 20kb reads, there are many others who are working hard to develop methods to utilize those now.) 

For the CPU and threading setup. The code will detect the number of vCPU and set the thread and partition number accordingly. When you have enough memory, you should set it to the max number of CPUs that you have. 500G RAM is good for almost all genomes perhaps up to 5Gb to 8Gb size. If you don't set the number of partitions, it will use the same number of partitions as the NTHREAD. In your case, I will just use 30 for both. However, there are cases if you set the NTHREAD to the physical number of CPU might help. (If you use Intel CPU, it is likely the 30 is the number of vCPU which is typically twice of the physical CPU number.)

**Comment by jelber2** [comment]
I have tried Peregrine-2021 with corrected PacBio CLR reads (corrected with Illumina reads) and the result compared to HiFi reads is that the general assembly structure seems recoverable but there are so many indels that cannot be corrected with short-read-based-correction of CLR reads that propagate into the Peregrine-2021 assembly. This is for prokaryotes, but I would imagine the same or worse for more complicated genomes. You can see a similar comparison with hifiasm I made a long time ago here https://github.com/chhylp123/hifiasm/issues/33
